### ISSUE TITLE
[Bug] Forge deps missing

### ISSUE THREAD

**Issue by mkubdev** [TheAlgorithms/Solidity#15]
In tests files, there is a missing dependency :

```js
import "forge-std/Test.sol";
```

![image](https://user-images.githubusercontent.com/50140834/175499321-0a86f58d-3044-4f0d-b881-8bae7cc73c60.png)

We should fix the repos according to this import for Foundry tests.

**Comment by Perelyn-sama** [comment]
Its there https://github.com/TheAlgorithms/Solidity/tree/main/lib

**Comment by mkubdev** [comment]
I close, solved by #18
