### ISSUE TITLE
[TEST] write foundry test for Sorts/SelectionSort.sol

### ISSUE THREAD

**Issue by mkubdev** [TheAlgorithms/Solidity#32]
I will definately look into it. must i write test for this selection sort before it will be merged?

_Originally posted by @Chiadikaobixo in https://github.com/TheAlgorithms/Solidity/issues/27#issuecomment-1257686258_

Add Foundry test for [SelectionSort.sol](https://github.com/TheAlgorithms/Solidity/blob/main/src/Sorts/SelectionSort.sol) (ex: [BubbleSort.t.sol](https://github.com/TheAlgorithms/Solidity/blob/main/src/Sorts/test/BubbleSort.t.sol))

**Comment by Fazil29** [comment]
I want to work on it.

**Comment by Fazil29** [comment]
Are you guys using truffle or remix for the project? If not then what tools are you guys using.

**Comment by Saurabhpatil-dev** [comment]
@Fazil29 As mentioned in the issue you should use the Foundry to write the tests. It is used for writing the unit tests for contracts.

**Comment by mkubdev** [comment]
> @Fazil29 As mentioned in the issue you should use the Foundry to write the tests. It is used for writing the unit tests for contracts.

@Fazil29 Yes, as @Saurabhpatil-dev suggest, you should use [Foundry](https://book.getfoundry.sh/forge/writing-tests).

**Comment by iSumitBanik** [comment]
@mkubdev , I have created PR for this issue. Added test for SelectionSort

**Comment by mkubdev** [comment]
Close since ##55 fix it.
