### ISSUE TITLE
Need to correct folder name from searchs to Searches 

### ISSUE THREAD

**Issue by priyda** [TheAlgorithms/Solidity#39]
[Solidity](https://github.com/TheAlgorithms/Solidity)/[src](https://github.com/TheAlgorithms/Solidity/tree/main/src)/Searchs/ should be changes to [Solidity](https://github.com/TheAlgorithms/Solidity)/[src](https://github.com/TheAlgorithms/Solidity/tree/main/src)/**Searches**.

I can work on to fix it :)

**Comment by Panquesito7** [comment]
Great catch! Feel free to work on it. 🙂

**Comment by priyda** [comment]
I fixed issue please review it.
