### ISSUE TITLE
[Feat]: Add the binary exponentation and merge sort algoritms

### ISSUE THREAD

**Issue by xeno097** [TheAlgorithms/Solidity#42]
### Context 

I'd like to perform the following changes to the repo:
- Binary exponentiation into the `src/Maths` folder
- Merge sort into the `src/Sorts` folder
- Add tests for the algorithms

### Extra

Considering #26, I'd like to know if it is preferable to implement the algorithms as libraries or contracts

**Comment by mkubdev** [comment]
> Considering https://github.com/TheAlgorithms/Solidity/issues/26, I'd like to know if it is preferable to implement the algorithms as libraries or contracts

Hello :wave: Do you like to be assigned for this task ?

Maybe we should focus on contracts as for now
