### ISSUE TITLE
update development environment

### ISSUE THREAD

**Issue by donBarbos** [TheAlgorithms/Solidity#43]
### suggestions:
* migrate from `npm` to `yarn`
* add `hardhat`
* use `chai`/`ethers`/`web3` for testing

ready to ensure the transition to best practices
[sample project](https://github.com/donBarbos/hardhat-template)

**Comment by iSumitBanik** [comment]
In my opinion, foundry does the job as we can write tests in Solidity itself. 
No knowledge of JS required to writes test cases.

Let's see what the contributors think about it.

**Comment by mkubdev** [comment]
Foundry is a powerfull toolkit for Solidity imo.

**Comment by iSumitBanik** [comment]
> Foundry is a powerfull toolkit for Solidity imo.
> * Foundry has faster compilation time
> * Test files written in Solidity
> * Foundry use git submodule instead of npm (This one can be discussed...)
> 

Agreed ++

**Comment by mkubdev** [comment]
I close since using Foundry is more efficient to manage the repos.
