### ISSUE TITLE
[TESTS] Add Foundry Tests for Linearsearch and BinarySearch

### ISSUE THREAD

**Issue by 0xSumitBanik** [TheAlgorithms/Solidity#57]
Currently there are no foundry tests written for LinearSearch and BinarySearch Contract.

- [x] Write tests for Linearsearch
- [x] Write tests for BinarySearch

**Comment by iSumitBanik** [comment]
PR #58  Created to address this issue. 👍🏽

**Comment by mkubdev** [comment]
Close since #58 fix it.
