### ISSUE TITLE
Incorrect Logic for Iterative Factorial Function

### ISSUE THREAD

**Issue by iSumitBanik** [TheAlgorithms/Solidity#6]
**ISSUE**

```solidity
        for (uint i= 2; i >= _n; i++){
            result *= i;
        }
```

The above code will fail in compilation as:
- i and n cannot be compared in second condition of for loop (as the data type is different (uint i and int n))
- The Second condition will never be true if the value of _n is more than 3. (It should have checked for less than <= _n)

**Solution**

Fix the logic for the "for" loop related to the iterative implementation of factorial.

**Comment by mkubdev** [comment]
I close since #7 is merged. (:
