### ISSUE TITLE
[BUG] Possible underflow in binary search 

### ISSUE THREAD

**Issue by Vikram710** [TheAlgorithms/Solidity#85]
Possible underflow in binary search [here](https://github.com/TheAlgorithms/Solidity/blob/1f4803962174e03cf0f363ad0f7540248ecaa174/src/Searches/BinarySearch.sol#L40C37-L40C38)
 
 example input arr = {2} target = 1
 
 middle will be 0 
 maximum = middle - 1; 0 -1 
 **0x11: If an arithmetic operation results in underflow or overflow outside of an unchecked { ... } block.**

**Comment by Adi9876** [comment]
@Panquesito7 assign me this task i can fix it !!
